### ISSUE TITLE
Quickly get to stripped down view

### ISSUE THREAD

**Issue by dannyhope** [remy/read-body#1]
The Readability Chrome extension has a keyboard shortcut (`) to view your current page with crap removed.

Any plans to make read-body work like this?

**Comment by remy** [comment]
It should be reasonably ease to write a plugin that captures the <kbd>`</kbd> key to reload the page into this read-body site…

**Comment by remy** [comment]
Thinking a greasemonkey like script:

```js
document.documentElement.addEventListener('keydown', e => e.which === 192 && window.location=`https://read.isthe.link?url=${window.location}`)
```

…I think!

**Comment by remy** [comment]
Okay, plugin will appear here in the next hour: https://chrome.google.com/webstore/detail/aongdhnmjmdaghgpobcdkoajiheioohl

(60 minutes is the timing Google gives you).

It'll read the <kbd>\`</kbd> key (and so long it isn't focused on a `textarea` or `input`), it'll reload the page on the read-body thingy.

**Comment by remy** [comment]
That's been published now if you want to give it an install.

**Comment by dannyhope** [comment]
Works great. Nice one! 👍
